# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [1]:
# Code Here
import numpy as np
A = np.array([[1402, 191],[1371,821],[949,1437],[147,1448]])
B = np.array([[1,2,3],[4,5,6]])
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of A and B 

In [4]:
# Code Here
print("Shape of A: ", A.shape)
print("Shape of B: ", B.shape)

Shape of A:  (4, 2)
Shape of B:  (2, 3)


## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [5]:
# Code Here
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])

1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [7]:
# Code Here (due to random data , your output might be different)
A = np.empty([3,3])
A[:,:] = 0
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
A = np.random.randint(1,10, size=(3,3))
print(A)

[[1 1 1]
 [7 8 6]
 [4 4 9]]


## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [22]:
# Code Here (due to random data , your output might be different)
import random

def generator(matrix):
    for x in range(0,matrix.shape[0]):
        for y in range(0,matrix.shape[1]):
            matrix[x][y] = random.randrange(1,10)
            
    return matrix

M1 = np.zeros((4,4))
M2 = np.zeros((4,4))

M1_fill = generator(M1)
M2_fill = generator(M2)
final = M1_fill + M2_fill

print("final output\n\n", final)

final output

 [[16. 10. 11. 15.]
 [12. 11.  6. 11.]
 [ 4. 12. 10. 16.]
 [ 9.  4. 11. 10.]]


In [23]:
M1

array([[7., 8., 4., 8.],
       [6., 5., 2., 3.],
       [1., 8., 5., 8.],
       [8., 3., 7., 9.]])

In [24]:
M2

array([[9., 2., 7., 7.],
       [6., 6., 4., 8.],
       [3., 4., 5., 8.],
       [1., 1., 4., 1.]])

In [25]:
M1_fill

array([[7., 8., 4., 8.],
       [6., 5., 2., 3.],
       [1., 8., 5., 8.],
       [8., 3., 7., 9.]])

In [26]:
M2_fill

array([[9., 2., 7., 7.],
       [6., 6., 4., 8.],
       [3., 4., 5., 8.],
       [1., 1., 4., 1.]])

## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 